name: AzureFunctionHealthCheck
metadata:
  template: false
  description: "Create function with health checks for monitor your application"
infra:
  provider: "bicep"
  path: "./infra"
services:
  function:
    project: ./src/function
    build:
      - python -m pip install -r requirements.txt
    language: python
    host: function